version: 2.1
orbs:
  jq: circleci/jq@2.2.0
jobs:
  publish:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: |
            cd .circleci
            ./publish.sh
workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
